name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'  
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest
    - name: Create .env file
      run: |
        echo "MLFLOW_TRACKING_URI=file:///api_ml/models/mlruns" >> .env
        echo "BEST_RUN_ID=236cf92d6a2e499b9a1d9935a18cbef7" >> .env
        echo "API_KEY=${{ secrets.API_KEY }}" >> .env
        echo "API_KEY_NAME=access_token" >> .env
    - name: Run tests
      run: |
        pytest api/tests/ 

  build-and-push:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/apiml:${{ github.sha }}